// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type GetImagesReq struct {
	OrderID string `path:"order_id"`
}

type GetImagesResponse struct {
	Images []string `json:"images"`
}

type UploadImagesReq struct {
	OrderID string `path:"order_id"`
}

type UploadResponse struct {
	Message string `json:"message"`
}
